## 指定启动的对象 (小写)
##consumer: 消费者
##producer: 生产者
##producer-console: 控制台版本的生产者(通过控制台手动输入主题、消息)
Type: producer
DirServer:
  - addr: 127.0.0.1
    port: 6001
  - addr: 127.0.0.1
    port: 6002
###LogLevel : UNKNOW < DEBUG < INFO < WARN < ERROR < FATAL
LogLevel: ERROR
###如果上面的Type为producer的话这里就是启动多个的生产者线程。 每个生产者的信息。 如果指定为producer-console则无效。
Producer:
  - name: producer1
    topic:
      - hello0
      - hello1
      - hello2
    msgLength: 1024  # byte
    totalLength: 64  # k
  - name: producer2
    topic:
      - hello3
      - hello4
    msgLength: 1024  # byte
    totalLength: 64  # k





